### PR TITLE
Fix missing logo on visa letters

### LINKED ISSUE #786: Logo missing from generated Speaker & Attendee visa letter PDFs
_Reported by kdrewien & kcristiano_

**To reproduce**

1. Go to Docs
2. Select one of the Visa letter options
3. Generate the PDF
4. View the PDF, there is no WordPress or WordCamp logo anywhere

**Expected behavior**

The `wpcs-logo.png` image should be visible in the PDF.

### PR DESCRIPTION
**Pull request by timiwahalahti**
Generated attendee and speaker visa letters didn't have the WPCS logo on them as intended. Fixed this by allowing wkhtmltopdf to access local files.

From [wkhtmltopdf docs](https://wkhtmltopdf.org/usage/wkhtmltopdf.txt)

```
      --enable-local-file-access      Allowed conversion of a local file to read
                                      in other local files.
```

Fixes #786

Props kdrewien, kcristiano, @yoga1103

### Screenshots

image

### How to test the changes in this Pull Request:

 1. Go to Docs
 2. Select one of the Visa letter options
 3. Generate the PDF
 4. View the PDF, there should be WPCS logo

### CODE REVIEW

File: public_html/wp-content/plugins/wordcamp-docs/classes/class-wordcamp-docs-pdf-generator.php [hunk 1]
```diff
@@ -72,7 +72,7 @@ public function generate_pdf_from_file( $source_file, $filename, $args = array()
 		$file = $this->get_tmp_folder( $filename );
 
 		$command = sprintf(
-			'wkhtmltopdf -d %d -T %s -R %s -B %s -L %s %s %s',
+			'wkhtmltopdf --enable-local-file-access -d %d -T %s -R %s -B %s -L %s %s %s',
```
Comment (iandunn) [inline public_html/wp-content/plugins/wordcamp-docs/classes/class-wordcamp-docs-pdf-generator.php:76]:
```suggestion
			// Allowing local file access is safe because the inputs to `$source_file` should have been escaped.
			'wkhtmltopdf --enable-local-file-access -d %d -T %s -R %s -B %s -L %s %s %s',
```

**Review by iandunn — APPROVED** [review]
It looks like this is the issue that caused that feature to be turned off by default:

https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4536

It seems like it should be safe to re-enable it, since all of our inputs are escaped 👍🏻
