### PR TITLE
Fix exchange rate issue with automated invoicing in qbo

### LINKED ISSUE #1250: Exchange Rate Issue with Automated Invoicing in QBO
**Describe the bug**

When an invoice is approved in the [Sponsor Dashboard](https://wordcamp.org/wp-admin/network/admin.php?page=sponsor-invoices-dashboard) and sent to QBO, if said invoice is in a currency other than USD, the exchange rate populates as 1:1 versus listing the actual rate for the date of creation. If an invoice is created directly in QBO in a currency other than USD, the exchange rate is populated appropriately. QBO Support was contacted in February of 2024, but no solution was offered. [This has been an issue since 2017.](https://a8c.slack.com/archives/C204BD7PT/p1484872496000472)

**To reproduce**

1. Go to any event site that has selected to run the event in a currency other than USD. For example, [WCEU](https://europe.wordcamp.org/2024/wp-admin/edit.php?post_type=wcb_sponsor_invoice).
2. Click on `Add New` in the upper left corner.
3. Once the test invoice has been created in EUR, send the invoice for approval. Then visit the main [Sponsors Invoice Dashboard](https://wordcamp.org/wp-admin/network/admin.php?page=sponsor-invoices-dashboard) and click `Approve` to the right of the test invoice.
4. Return to the WCEU sponsor invoice dashboard, and after opening QBO to the WPCS business, click on the link in the upper right corner `View QBO Invoice`

**Expected behavior**

You will notice the exchange rate in the upper left corner will reflect 1 EUR = 1 USD

[example.pdf](https://github.com/WordPress/wordcamp.org/files/14313919/example.pdf)

**System (please complete the following information):**

 - Device: laptop
 - OS: iOS
 - Browser Chrome
 - Version 121.0.6167.160

### PR DESCRIPTION
**Pull request by outdoor2kode**
In the 2017 discussion mentioned in the issue, it can be seen that at that time, even if you didn't provide an exchange rate when calling the QBO API, QBO would automatically fill in the exchange rate for you. So I tested in this direction in the first place but then found that if you don't include the `ExchangeRate` in the API call now, QBO will automatically set the value to `1`: `"CurrencyRef":{"value":"EUR","name":"Euro"},"ExchangeRate":1`.

After searching, I found [discussions](https://help.developer.intuit.com/s/question/0D50f00005AZZ9DCAX/hi-how-can-i-set-quickbooks-to-update-the-exchange-rate-when-the-invoice-is-created-from-the-api) indicating that the QBO invoice API does not support automatically providing the `ExchangeRate` (perhaps they changed the rules at some point after 2017). You have to get the value yourself and include it in the payload. So here I used the get exchange rate [API](https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/exchangerate#get-an-exchangerate-for-an-individual-currency-code) also from QBO (the sample on the page doesn't work, but the API actually works..).

In addition, the local QBO connection is also fixed. It turned out that the relevant SDK was missing, and installing it solved the issue.

Fixes #1250

### Screenshots

**Exchange rate now correctly displays**
|| Invoice manually created in QBO | Invoice sent from WordCamp |
|-|-|-|
| EUR | Screenshot 2024-05-23 at 20 44 34 | Screenshot 2024-05-23 at 20 44 17 |
| JPY | Screenshot 2024-05-23 at 20 57 58 | Screenshot 2024-05-23 at 20 57 43 |

### How to test the changes in this Pull Request:

1. `composer update`.
2. Follow https://github.com/WordPress/wordcamp.org/tree/production/public_html/wp-content/plugins/wordcamp-qbo#wordcamp-qbo to set up QBO locally.
3. Add a new sponsor invoice here in `/wp-admin/post-new.php?post_type=wcb_sponsor_invoice`.
    - If the community dropdown does not display any country options, click on "Delete Cache" and then refresh.
4. Approve the invoice you added in `/wp-admin/network/admin.php?page=sponsor-invoices-dashboard&section=submitted`
5. Go to https://app.sandbox.qbo.intuit.com/app/invoices and enter the invoice editing screen.
6. Check if exchanges are correct. (you can test with multiple currencies)

### CODE REVIEW

File: public_html/wp-content/plugins/wordcamp-qbo/wordcamp-qbo.php [hunk 1]
```diff
@@ -493,9 +493,31 @@ protected static function build_qbo_create_invoice_request( int $invoice_id ) {
...
+					'headers' => array(
+						'Authorization' => $oauth_header,
+						'Accept'        => 'application/json',
+						'Content-Type'  => 'application/json',
+					),
+				)
+			);
+
+			$body          = json_decode( wp_remote_retrieve_body( $response ), true );
+			$exchange_rate = $body['ExchangeRate']['Rate'];
```
Comment (pkevan) [inline public_html/wp-content/plugins/wordcamp-qbo/wordcamp-qbo.php]: we should probably add some error handling around this - for if the API returns an error or isn't available

Comment (pkevan) [reply public_html/wp-content/plugins/wordcamp-qbo/wordcamp-qbo.php]: what do you think about some kind of caching around the lookup too?

Comment (renintw) [reply public_html/wp-content/plugins/wordcamp-qbo/wordcamp-qbo.php:514]: > we should probably add some error handling around this - for if the API returns an error or isn't available

👍 Will add that.

> what do you think about some kind of caching around the lookup too?

看起來 Quickbook 每 4 小時就會更新一次 exchange rate，所以我們設定的話應該要更短，不然不知道他是何時開始更新的。
https://quickbooks.intuit.com/learn-support/en-ca/help-article/multicurrency/learn-multicurrency-quickbooks-online/L5krkKQi8_CA_en_CA#:~:text=Foreign%20currency%20values%20are%20automatically,Markit%2C%20an%20information%20services%20company.

It looks like QuickBooks updates the exchange rates every 4 hours, so if we were to set a cache, it needs to have a shorter interval to ensure we get the latest rates, since we don't know exactly when their updates begin.
[Source](https://quickbooks.intuit.com/learn-support/en-ca/help-article/multicurrency/learn-multicurrency-quickbooks-online/L5krkKQi8_CA_en_CA#:~:text=Foreign%20currency%20values%20are%20automatically,Markit%2C%20an%20information%20services%20company.)

The API call is triggered only when an invoice is approved. I saw that this month, the maximum number of approvals in one day is 16, and they might be in different currencies. It seems to me that we don't need to implement caching for this. What do you think?

Comment (outdoor2kode) [reply public_html/wp-content/plugins/wordcamp-qbo/wordcamp-qbo.php]: > we should probably add some error handling around this - for if the API returns an error or isn't available

👍 Will add that.

> what do you think about some kind of caching around the lookup too?

[It](https://quickbooks.intuit.com/learn-support/en-ca/help-article/multicurrency/learn-multicurrency-quickbooks-online/L5krkKQi8_CA_en_CA#:~:text=Foreign%20currency%20values%20are%20automatically,Markit%2C%20an%20information%20services%20company.) looks like QuickBooks updates the exchange rates every 4 hours, so if we were to set a cache, it needs to have a shorter interval to ensure we get the latest rates, since we don't know exactly when their updates begin.

The API call is triggered only when an invoice is approved. I saw that this month, the maximum number of approvals in one day is 16, and they might be in different currencies. It seems to me that we don't need to implement caching for this. What do you think?

Comment (pkevan) [reply public_html/wp-content/plugins/wordcamp-qbo/wordcamp-qbo.php]: it was unclear how often this code was called - so not adding caching based on a low frequency makes sense. We could always add a code comment saying as much to help in the future.

Comment (outdoor2kode) [reply public_html/wp-content/plugins/wordcamp-qbo/wordcamp-qbo.php]: Good point.

Comment (outdoor2kode) [reply public_html/wp-content/plugins/wordcamp-qbo/wordcamp-qbo.php]: Comment added: 8181f66
Error handling: b500574

File: public_html/wp-content/plugins/wordcamp-qbo/wordcamp-qbo.php [hunk 2]
```diff
@@ -493,9 +493,46 @@ protected static function build_qbo_create_invoice_request( int $invoice_id ) {
...
+				array(
+					'timeout' => self::REMOTE_REQUEST_TIMEOUT,
+					'headers' => array(
+						'Authorization' => $oauth_header,
+						'Accept'        => 'application/json',
+						'Content-Type'  => 'application/json',
+					),
+				)
+			);
+			Logger\log( 'remote_request', compact( 'currency_code', 'response' ) );
```
Comment (pkevan) [inline public_html/wp-content/plugins/wordcamp-qbo/wordcamp-qbo.php:516]: unsure if this is debugging code left in or needed?

Comment (outdoor2kode) [reply public_html/wp-content/plugins/wordcamp-qbo/wordcamp-qbo.php:516]: This code appears in other parts as well. You can see logs on the terminal and can also check them using `wp wc-misc format-log wp-content/debug.log` as specified in the QBO [Readme](https://github.com/WordPress/wordcamp.org/tree/production/public_html/wp-content/plugins/wordcamp-qbo#testing).

Comment (outdoor2kode) [reply public_html/wp-content/plugins/wordcamp-qbo/wordcamp-qbo.php:516]: It appears that it can also let you see the production logs. ([ref](https://a8c.slack.com/archives/C204BD7PT/p1484872297000471))

Comment (pkevan) [reply public_html/wp-content/plugins/wordcamp-qbo/wordcamp-qbo.php:516]: ok - but it's kind of pointless logging every time we do a lookup isn't it?

Comment (outdoor2kode) [reply public_html/wp-content/plugins/wordcamp-qbo/wordcamp-qbo.php:516]: I don't feel strongly about it; just following the practice here. Perhaps there was a discussion that every API call should have a logger and what benefits it would bring? I'm not sure. However, removing it here makes sense to me since it isn't a critical call. What do you think?
