### PR TITLE
Prevent broken Tickets pages when tickets have been sold

### LINKED ISSUE #402: CampTix: Prevent broken Tickets pages when shortcode removed
Removing the shortcode from the page breaks the ability to refund tickets, etc.

From https://wordpress.slack.com/archives/C08M59V3P/p1585075640140900:

<blockquote>
Ian Dunn: Aside to ^: we could add some code that would prevent removing the shortcode from the page after a ticket has been purchased<br/><br/>

Kevin Cristiano: Good idea. I just recreated the page with the proper slug, looks like it was renamed and manual refunds are available, Trying mass refund one last time

Ryan Marks: Some additional use cases to consider for pages containing the shortcode: Prevent the page slug from being renamed. Prevent the page from being deleted.
</blockquote>

### PR DESCRIPTION
**Pull request by timiwahalahti**
Removing the shortcode from the tickets page, or changing its slug or publicity breaks the ability to refund tickets, etc.

This PR aims to prevent removal of camptix shortcode, change in page publicity or slug when tickets have been sold.

Fixes #402 

Props @iandunn 

### TODO

- [x] Add notification on edit view to tell that tickets have been sold so these actions cannot be taken
- [x] Test Gutenberg
- [x] Move the function to a better place

### Screenshots

Warning when changes are prevented, block editor.
image

Warning when changes are prevented, classic editor.
image

Error when changes are tried, block editor.
image

Error when changes are tried, classic editor.
image

### How to test the changes in this Pull Request:

1. Open WordCamp site dashboard, ensure that no tickets have been sold and tickets page is draft
2. Update the tickets page, and change slug for example -> updating should work
3. Publish the page, remove camptix shortcode this time -> updating should work
4. Add the shortcode back and buy one ticket
5. Open the tickets page in classic editor -> you should see warning
6. Open the tickets page in block editor -> you should see warning
7. Update the page on block editor, change slug -> you should get error
8. Update the page on block editor, remove camptix shortcode -> you should get error
9. Update the page on classic editor, try to change staus back to draft -> you should get error

### CODE REVIEW

**Review by iandunn — APPROVED** [review]
LGTM 👍🏻

File: public_html/wp-content/plugins/camptix/camptix.php [hunk 1]
```diff
@@ -5395,6 +5400,198 @@ function shortcode_callback( $atts ) {
...
+		// Cannot change the visibility of the page anymore.
+		if ( 'publish' !== $postarr['post_status'] || ! empty( $postarr['post_password'] ) ) {
+			$maybe_empty = true;
+			$message =
+				__( 'You cannot unpublish or make the page private because tickets have been sold.', 'wordcamporg' ) . ' ' .
+				__( 'Doing that would break the links on ticket emails sent to attendees.', 'wordcamporg' );
+		}
+
+		// Cannot change the slug anymore.
+		if ( $postarr['post_name'] !== $post_before->post_name ) {
```
Comment (StevenDufresne) [inline public_html/wp-content/plugins/camptix/camptix.php:5477]: I think after you refactored in 17b1e53f8cec871f8418864c999ede12f73f241a `$post_before` is no longer in scope.

**Comment by StevenDufresne** [comment]
I had to revert this PR. 

See:
https://wordpress.slack.com/archives/C08M59V3P/p1696990191433489
